<?php

/**
 * Implementation of hook_ctools_plugin_api().
 */
function mn_kml_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "openlayers" && $api == "openlayers_layers") {
    return array("version" => 1);
  }
}

/**
 * Implementation of hook_menu().
 */
function mn_kml_menu() {
  $items = array();
  $items['admin/settings/mn_kml'] = array(
    'title' => 'KML settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mn_kml_manage_maps'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 * Page callback for Manage Maps.
 */
function mn_kml_manage_maps() {
  $form = array();
  $defaults = variable_get('mn_kml_paths', '');
  
  $form['mn_kml_paths'] = array(
    '#type' => 'textfield',
    '#title' => t('Add KML'),
    '#description' => t('Add the URL of your KML or the relative path to a file within your Drupal installation.'),
    '#default_value' => $defaults,
  );
  return system_settings_form($form);
}

/**
 * Implementation of hook_openlayers_postrender_alter().
 */
function mn_kml_openlayers_postrender_alter(&$map) {
  $contexts = array_shift(context_get());
  foreach ($contexts as $context) {
    if ($context->name == 'mn-display_mode-map') {
      $kmls = array(variable_get('mn_kml_paths', ''));
      foreach ($kmls as $kml) {
        if ($kml != '') {
          $map['layers'][$kml] = $kml;
          $map['layer_activated'][$kml] = $kml;
          // $map['layer_switcher'][$kml] = $kml;
        }
      }
    }
  }
}

/**
 * Implementation of hook_openlayers_layers().
 */
function mn_kml_openlayers_layers() {
  $layers = array();
  $kmls = array(variable_get('mn_kml_paths', ''));
  foreach ($kmls as $kml) {
    //Build Layer
    $layer = new StdClass();
    $layer->api_version = 1;
    $layer->name = $kml;
    $layer->title = $kml;
    $layer->description = $view->description . ' - ' . $data->display_title;
    $layer->data = array(
      'layer_type' => 'openlayers_layer_type_kml',
      'projection' => array('4326', '900913', '4269'),
      'baselayer' => FALSE,
      'type' => 'KML',
      'url' => $kml,
      'options' => array(),
    );
    $layers[$layer->name] = $layer;
  }
  return $layers;
}
